
library(Signac) # 0.1.5 ..
library(Seurat) # 3.0.2 ..
library(Gviz) # ..
library(biomaRt) # ..
library(dplyr) # ..
library(plyranges) # ..
library(EnsDb.Hsapiens.v86) # ..
library(cicero)
library(data.table)
library(openxlsx)
library(zoo) # has rollapply function required for CalculateCoverages
library(here)
library(tibble)

# identify celltype-specific dac between control and diabetes and generate granges object
FindDacGRanges <- function(seuratAtacSub, clusterID) {
  Idents(seuratAtacSub) <- "celltype"
  DefaultAssay(seuratAtacSub) <- 'peaks'
  dac <- FindMarkers(seuratAtacSub, ident.1 = clusterID,
                     test.use = 'LR', latent.vars = "peak_region_fragments") # find dac
  dac <- dac[dac$p_val < 0.05, ]
  cf <- ClosestFeature(rownames(dac), annotation=EnsDb.Hsapiens.v86, sep=c(':','-'))
  dac <- cbind(dac, symbol=cf$gene_name, distance=cf$distance)
  dacGRanges <- StringToGRanges(regions = rownames(dac[dac$p_val < 0.05, ]), sep = c(":", "-"))
  mcols(dacGRanges)$lfc <- dac$avg_logFC # add the log fold change as a meta data column with Gviz package
  mcols(dacGRanges)$closestGene <- dac$gene
  mcols(dacGRanges)$distance <- dac$distance
  return(dacGRanges)
}

# identify celltype-specific deg 
FindDegGRanges <- function(seuratRnaSub, clusterID) {
  Idents(seuratRnaSub) <- "celltype"
  DefaultAssay(seuratRnaSub) <- 'SCT'
  deg <- FindMarkers(seuratRnaSub, ident.1 = clusterID) # find all cluster-specific deg
  deg <- deg[deg$p_val < 0.05, ]
  human = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
  bm <- getBM(attributes = c("hgnc_symbol","chromosome_name", "start_position", "end_position","ensembl_gene_id"),
              filters = "hgnc_symbol", values = rownames(deg), mart = human) # get genomic coordinates of degs
  deg$hgnc_symbol <- rownames(deg)
  degCoord <- merge(bm, deg, by = "hgnc_symbol")
  degGRanges <- GRanges(seqnames = paste0("chr",degCoord$chromosome_name), 
                        ranges = IRanges(start = degCoord$start_position, end = degCoord$end_position),
                        lfc = degCoord$avg_logFC, symbol = degCoord$hgnc_symbol, pval = degCoord$p_val)
  return(degGRanges)
}


PullRegionGRanges <- function(gene, extend) {
  seqlevels <- c(seq(1,24),"X","Y")
  human = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
  bm <- getBM(attributes = c("hgnc_symbol","chromosome_name", "start_position", "end_position","ensembl_gene_id"),
              filters = "hgnc_symbol", values = gene, mart = human) %>%
    dplyr::filter(chromosome_name %in% seqlevels)
  regionStart <- bm$start_position - extend
  regionEnd <- bm$end_position + extend
  chr <- paste0("chr", bm$chromosome_name)
  regionGRanges <- GRanges(chr, paste0(regionStart,"-",regionEnd))
  return(regionGRanges)
}


#' CalculateCoverages
#'
#' Calculate normalized read coverage per base per cell group
#'
#' @param reads Dataframe containing reads for a region, generated by \code{\link{GetReadsInRegion}}
#' @param cells.per.group Number of cells in each group. Must be a named vector. Used for normalization of track heights.
#' @param reads.per.group Average number of reads per group.
#' @param scale.factor Scaling factor for track height. If NULL, use the median group scaling factor
#' determined by total number of fragments sequences in each group.
#' @param window Smoothing window to use
#' @param verbose Display messages
#'
#' @importFrom zoo rollapply
#' @importFrom stats median
#' @importFrom dplyr group_by mutate summarize arrange ungroup
#' @export
CalculateCoverages <- function(
  reads,
  cells.per.group,
  reads.per.group,
  scale.factor = NULL,
  window = 100,
  verbose = TRUE
) {
  if (verbose) {
    message("Computing coverage per base")
  }
  templist <- list()
  y <- 1
  addbases <- 40
  n_allocate <- sum(reads$length)
  templist$position <- rep(x = 0, n_allocate)
  templist$value <- rep(x = 0, n_allocate)
  templist$cell <- rep(x = '0', n_allocate)
  templist$group <- rep(x = '0', n_allocate)
  startpos <- reads[,][['start']]
  endpos <- reads[,][['end']]
  cellnames <- as.character(x = reads[,][['cell']])
  groupnames <- as.character(x = reads[,][['group']])
  for (i in seq_len(length.out = nrow(x = reads))) {
    interval <- (startpos[[i]]-addbases):(endpos[[i]]+addbases)
    for (j in interval) {
      bases_away <- abs(min((j - startpos[[i]]), (endpos[[i]] - j)))
      if ((endpos[[i]] > j) & (j > startpos[[i]])) {
        internal <- TRUE
      } else {
        internal <- FALSE
      }
      templist$position[y] <- j
      templist$value[y] <- WeightAccessibility(
        bases_away = bases_away,
        internal = internal,
        inflection = (addbases/2)
      )
      templist$cell[[y]] <- cellnames[[i]]
      templist$group[[y]] <- groupnames[[i]]
      y <- y + 1
    }
  }
  expanded <- as.data.frame(x = t(x = do.call(what = rbind, args = templist)), stringsAsFactors = FALSE)
  expanded$position <- as.numeric(x = expanded$position)
  expanded$value <- as.numeric(x = expanded$value)
  posrange <- min(expanded$position):max(expanded$position)
  fill_positons <- data.frame(
    position = rep(posrange, length(unique(expanded$group))),
    value = 0,
    cell = NA,
    group = unlist(lapply(unique(expanded$group), function(x) rep(x, length(posrange)))),
    row.names = NULL
  )
  expanded <- rbind(expanded, fill_positons)
  if (is(object = reads$group, class2 = 'factor')) {
    expanded$group <- factor(x = expanded$group, levels = levels(reads$group))
  }
  read_scale <- reads.per.group * cells.per.group
  if (is.null(x = scale.factor)) {
    scale.factor <- median(x = read_scale)
  }
  expanded$norm.value <- expanded$value / read_scale[expanded$group] * scale.factor
  expanded <- group_by(.data = expanded, position, group)
  coverages <- summarize(.data = expanded, total = sum(norm.value))
  coverages <- group_by(.data = coverages, group)
  coverages <- arrange(.data = coverages, position)
  if (!is.na(x = window)) {
    coverages <- mutate(.data = coverages, coverage = rollapply(
      data = total,
      width = window,
      FUN = mean,
      align = 'center',
      fill = NA
    ))
  } else {
    coverages$coverage <- coverages$total
  }
  coverages <- ungroup(x = coverages)
  return(coverages)
}


#' Weight accessibility score based on distance from Tn5 integration site
#'
#' @param bases_away Number of bases from the Tn5 integration site
#' @param internal Whether the postion is within a fragment (TRUE) or flanking a fragment (FALSE)
#' @param rate Rate of score decay. Lower value gives steeper slope in sigmoid function.
#' @param inflection Inflection point for sigmoid weight function. This base will have weight
#' equal to 0.5
WeightAccessibility <- function(bases_away, internal, rate = 2, inflection = 20) {
  bases_away <- bases_away - inflection
  weights <- exp(-bases_away / rate)/(1 + exp(-bases_away / rate))
  weights <- round(x = weights, digits = 3)
  if (weights == 0 & internal) {
    weights <- -0.1
  }
  return(weights)
}


FindCoverageRegion <- function(seuratAtacSub, clusterID, regionGRanges, downsample) {
  Idents(seuratAtacSub) <- "celltype"
  cells <- colnames(x = seuratAtacSub)
  reads <- GetReadsInRegion(seuratAtacSub, assay = 'peaks', region = regionGRanges)
  cells.per.group <- CellsPerGroup(object = seuratAtacSub, group.by = NULL)
  reads.per.group <- AverageCounts(object = seuratAtacSub, group.by = NULL, verbose = FALSE)
  coverages <- suppressWarnings(CalculateCoverages(
    reads = reads,
    cells.per.group = cells.per.group,
    reads.per.group = reads.per.group,
    window = 100,
    verbose = TRUE
  ))
  downsample <- downsample
  chromosome <- as.character(x = seqnames(x = regionGRanges))
  start.pos <- start(x = regionGRanges)
  end.pos <- end(x = regionGRanges)
  stepsize <- 1 / downsample
  total_range <- end.pos - start.pos
  steps <- ceiling(x = (total_range / stepsize))
  retain_positions <- seq(from = start.pos, to = end.pos, by = stepsize)
  downsampled_coverage <- coverages[coverages$position %in% retain_positions, ]
  ymax <- signif(x = max(downsampled_coverage$coverage, na.rm = TRUE), digits = 2)
  downsampled_coverage <- downsampled_coverage[!is.na(x = downsampled_coverage$coverage), ]
  return(downsampled_coverage)
}


PeaksToGvizTrack <- function(downsampled_coverage, clusterID, regionGRanges) {
  chr <- regionGRanges@seqnames@values
  peaks <- dplyr::filter(downsampled_coverage, group ==clusterID)
  peaksGRanges <- GRanges(seqnames = chr, ranges = IRanges(start = peaks$position, width = 1),
                          coverage = peaks$coverage)
  peaksTrack <- DataTrack(range = peaksGRanges, data = "coverage", type = "histogram")
  return(peaksTrack)
}


EncodeTfbsTrack <- function(dacOverlap, name, clusterID = NULL, filter = FALSE) {
  url <- "http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/encRegTfbsClustered.txt.gz"
  if(file.exists(basename(url))) { # download encode tfbs if not present in environment
    encodeTfbs <- fread(basename(url))
  } else {
    download.file(url, dest = basename(url))
    encodeTfbs <- fread(basename(url))
  }
  
  colnames(encodeTfbs) <- c("bin","chrom","start","end","name","score","sourceCount","sourceIds","sourceScores")
  encodeTfbs <- encodeTfbs[encodeTfbs$chrom == levels(regionGRanges@seqnames@values),] #subset for chromosome of interest to reduce size of df
  encodeTfbsAnno <- makeGRangesFromDataFrame(encodeTfbs)
  encodeTfbsAnno$id <- encodeTfbs$name # add a metadata column with the TF name
  encodeTfbsAnno <- join_overlap_intersect(encodeTfbsAnno, dacOverlap) # subset to dac region of interest
  
  color = "black"
  if(isTRUE(filter)) {
    motifFile <- "analysis_control/motifs.PCT_vs_PTKIM1.xlsx" # calculated by signacAtacFindMotif.R
    enriched.motifs <- read.xlsx(motifFile) %>%
      dplyr::select(motif, fold.enrichment, pvalue, motif.name) %>%
      dplyr::filter(pvalue < 0.05)
    encodeTfbsAnno <- encodeTfbsAnno[encodeTfbsAnno$id %in% enriched.motifs$motif.name, ]  # remove motifs that are not enriched
    color = "darkgreen" # change enriched motifs color to green (all motifs are increased in this list)
  }
  
  if (length(encodeTfbsAnno$tf) > 10) { # tf labels will overlap if there are too many
    encodeTfbsTrack <- AnnotationTrack(encodeTfbsAnno, name = name,
                                       col = color, fill = color, fontcolor = color, id = encodeTfbsAnno$id, showId = FALSE)
  } else {
    encodeTfbsTrack <- AnnotationTrack(encodeTfbsAnno, name = name, id = encodeTfbsAnno$id, 
                                       groupAnnotation = "id", col = color, fill = color, fontcolor = color, showId = FALSE)
  }
  return(encodeTfbsTrack)
}

######################3

gene = "HNF4A"
atac_clusterID <- "PCT"
rna_clusterID <- "PT"
seqlevels <- c(seq(1,24),"X","Y")
extend <- 50000 # extend region beyond gene body up- and downstream
downsample <- 100 # reduce number of points to plot for histograms of atac coverage
motifFile <- "" 

# read in snATACseq and snRNAseq datasets after preprocessing
atacAggr <- readRDS("cellranger_atac_prep/chromVar.atacAggr_sub97_control.rds")
fragment.path <- "cellranger_atac_aggr_control/outs/fragments.tsv.gz"
Idents(atacAggr) <- "celltype"

rnaAggr <- readRDS("cellranger_rna_prep/rnaAggr_control.rds")
Idents(rnaAggr) <- "celltype"
DefaultAssay(rnaAggr) <- "SCT"


# find dac 
dac <- read.xlsx("analysis_control/dar.celltype.control.xlsx",
                 sheet = atac_clusterID, rowNames = TRUE) %>%
                rownames_to_column(var = "coord") %>%
                dplyr::filter(p_val_adj < 0.05)
cf <- ClosestFeature(dac$coord, annotation=EnsDb.Hsapiens.v86, sep=c(':','-'))
dac <- cbind(dac, symbol=cf$gene_name, distance=cf$distance)
dacGRanges <- StringToGRanges(regions = dac$coord, sep = c(":", "-"))
mcols(dacGRanges)$lfc <- dac$avg_logFC # add the log fold change as a meta data column with Gviz package
mcols(dacGRanges)$closestGene <- dac$symbol
mcols(dacGRanges)$distance <- dac$distance


# find deg 
deg <- read.xlsx("analysis_control/deg.celltype.control.xlsx",
                 sheet = rna_clusterID, rowNames = TRUE) %>%
  rownames_to_column(var = "gene") %>%
  dplyr::filter(p_val_adj < 0.05)
human = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
bm <- getBM(attributes = c("hgnc_symbol","chromosome_name", "start_position", "end_position","ensembl_gene_id"),
            filters = "hgnc_symbol", values = deg$gene, mart = human) # get genomic coordinates of degs
deg$hgnc_symbol <- deg$gene
degCoord <- merge(bm, deg, by = "hgnc_symbol")
degGRanges <- GRanges(seqnames = paste0("chr",degCoord$chromosome_name), 
                      ranges = IRanges(start = degCoord$start_position, end = degCoord$end_position),
                      lfc = degCoord$avg_logFC, symbol = degCoord$hgnc_symbol, pval = degCoord$p_val)



# find differentially expressed motifs 
enriched.motifs <- read.xlsx("analysis_control/motifs.celltype.control.xlsx",
                             sheet = atac_clusterID, rowNames = TRUE) %>%
                            dplyr::filter(pvalue < 0.05)
# return genomic coords for the gene of interest and extend the coords up- and downstream
regionGRanges <- PullRegionGRanges(gene, extend)


# determine the atac peak coverage within the region of interest
atacAggrsub <- subset(atacAggr, ident = atac_clusterID)
downsampled_coverage <- FindCoverageRegion(atacAggrsub, clusterID = atac_clusterID, regionGRanges, downsample) 

# create Gviz tracks out of the downsampled peaks to plot with GViz
peakTrack <- PeaksToGvizTrack(downsampled_coverage, clusterID = atac_clusterID, regionGRanges)
peakTrack@name <- "PEAKS"
ymax <- max(peakTrack@data) # determine max peak height to scale data tracks


degOverlap <- join_overlap_intersect(degGRanges, regionGRanges) %>%
  dplyr::filter(symbol == gene)
degTrack <- DataTrack(range = degOverlap, data = "lfc", genome = "hg38")

# generate a track of diff. access. chromatin between DM vs. Ctrl that overlap with region
dacOverlap <- join_overlap_intersect(dacGRanges, regionGRanges)
dacTrack <- DataTrack(range = dacOverlap, data = "lfc", genome = "hg38") 

# select color for generegiontrack fill based on whether the gene in the degTrack is up- or down-regulated
colorDeg = "darkgray"
if (is.null(degOverlap$lfc)) {
  print("No differentially expressed genes present")
  colorDeg = "darkgray"
} else if (degOverlap$lfc > 0) {
  print ("Gene is upregulated")
  colorDeg = "darkgreen"
} else if (degOverlap$lfc < 0) {
  print("Gene is downregulated")
  colorDeg = "darkred"
} 



# set up annotation tracks
# filters <- AnnotationFilterList(GeneBiotypeFilter(value = 'protein_coding'), SeqNameFilter(chr))
edb <- EnsDb.Hsapiens.v86
filters <- AnnotationFilterList(GeneNameFilter(gene))
gr <- getGeneRegionTrackForGviz(edb, filter = filters)
# gr <- getGeneRegionTrackForGviz(edb, chromosome = chr, start = regionStart, end = regionEnd)
# gr@seqnames@values <- paste0("chr", gr@seqnames@values) # change contigs to ucsc standard
# gr <- renameSeqlevels(gr, chr) # change contigs to ucsc standard
grTrack <- GeneRegionTrack(range = gr, transcriptAnnotation = "symbol", feature = "gene",
                           name = gene, collapseTranscripts = "longest", shape = "arrow", fill = colorDeg, col = colorDeg, stacking = "dense")
grTrack <- grTrack[symbol(grTrack) == gene] # remove gene models that are up- or downstream of desired gene
displayPars(grTrack) <- list(size=2) # ensure track is large enough to display gene name


# add a GWAS track for a SNP in HIST1H2AC assoc with HTN
gwas <- StringToGRanges("chr6:26132842-26132842", sep = c(":", "-"))
gwasTrack <- AnnotationTrack(gwas, name = "GWAS")

# create a track that encodes the genomic coordinates and a track with an ideogram
axTrack <- GenomeAxisTrack(labelPos="above")
idxTrack <- IdeogramTrack(genome="hg38", chromosome=chr)


# annotate with encode transcription factor chip-seq peaks using the ucsc genome annotations
# see additional options here: http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/
# This track shows regions of transcription factor binding derived from a large collection of 
# ChIP-seq experiments performed by the ENCODE project between February 2011 and November 2018, 
# spanning the first production phase of ENCODE ("ENCODE 2") through the second full production phase ("ENCODE 3").
# load reference genomes
# find tfbs in diff. access regions filter parameter will select only enriched motifs in the dac areas
tfbsTrack <- EncodeTfbsTrack(dacOverlap, name = "TFBS", clusterID = clusterID, filter = TRUE)

# create an overlay track
overlay <- OverlayTrack(trackList = peakTrack)


# set chromosome, regionStart, and regionEnd variables and plot individual tracks
chr <- levels(regionGRanges@seqnames@values)
regionStart <- start(regionGRanges)
regionEnd <- end(regionGRanges)

# read in cicero connections generated by ciceroFindConns.R
connsFile1 <- paste0("analysis_control/ccans/ciceroConns.control.",atac_clusterID,".csv")
conns1 <- fread(connsFile1) 
c1f <- dplyr::filter(conns1, grepl(chr, Peak1))

# create highlights using the dac track
ymax <- max(peakTrack@data) # scale y axis for peaks
hltrack = HighlightTrack(trackList = list(peakTrack), range = dacOverlap) 
hl1 <- HighlightTrack(trackList = peakTrack, range = dacOverlap, ylim = c(0,ymax))


# create integrated plot of all tracks
plots <- plot_connections(c1f, chr, regionStart, regionEnd, 
                          return_as_list = TRUE, coaccess_cutoff = 0.30, alpha_by_coaccess = FALSE, 
                          connection_ymax = 0.7) 
# if coaccess cutoff is too high
# cicero may throw an error that reads "1: In max(sub2$height, na.rm = TRUE) :
#  no non-missing arguments to max; returning -Inf
# 2: In plot_connections(c1, chr, regionStart, regionEnd, comparison_track = c2,  :
#  comparison_ymax calc failed"
displayPars(plots[[1]]) <- list(size=2) # increase height of connection tracks in plot
plots[[3]] <- hl1
# plots[[4]] <- tfbsTrack
plots[[4]] <- grTrack
# plots[[1]]@dp@pars$fontsize <- 12
plots[[1]]@dp <- plots[[3]]@dp # make track fonts and titles in the same theme
plots[[5]] <- axTrack

geneModelFile <- paste0("plots/geneModel.conns.",gene,".",atac_clusterID,".pdf")
pdf(file = geneModelFile, width=10, height=6)
plotTracks(plots, chr, from = regionStart, to = regionEnd, ylim = c(0,ymax), sizes=c(2,0.25,2,1,0.5))
dev.off()

geneModelFile <- paste0("plots/geneModel.conns.",gene,".",atac_clusterID,".png")
png(file = geneModelFile, type = "cairo")
plotTracks(plots, chr, from = regionStart, to= regionEnd, ylim = c(0,ymax), sizes=c(2,0.25,2,1,0.5))
dev.off()

# compare the connections to genehancer database
# output from ucsc tablebrowser https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=805970397_7oqVCYOib9aK3Nnux8GwIMmYSHWK&clade=mammal&org=&db=hg38&hgta_group=allTracks&hgta_track=geneHancer&hgta_table=geneHancerRegElementsDoubleElite&hgta_regionType=range&position=&hgta_outputType=primaryTable&hgta_outFileName=hnf4a_geneHancer.txt
gh_hnf4a <- read.table("analysis_control/ccans/geneHancer/hnf4a_geneHancer.txt", header = TRUE)
peak1 <- paste0(gh_hnf4a$geneHancerChrom,"_",gh_hnf4a$geneHancerStart,"_",gh_hnf4a$geneHancerEnd)
peak2 <- paste0(gh_hnf4a$chrom,"_",gh_hnf4a$chromStart,"_",gh_hnf4a$chromEnd)
gh_conns <- data.frame(Peak1 = peak1, Peak2 = peak2, coaccess = 0.5)

c1f$in_gh <- compare_connections(c1f, gh_conns, maxgap = 100)
# c1f[c1f$in_gh == "TRUE",]

c1f$conn_color <- "indianred2"
c1f$conn_color[c1f$in_gh] <- "lightskyblue2"

gh_plots <- plot_connections(c1f, chr, regionStart, regionEnd, connection_color = "conn_color",
                          return_as_list = TRUE, coaccess_cutoff = 0.3, alpha_by_coaccess = FALSE, 
                          connection_ymax = 0.7, comparison_track = gh_conns, connection_color_legend = FALSE) 
displayPars(plots[[1]]) <- list(size=2) # increase height of connection tracks in plot
gh_plots[[3]] <- hl1
# plots[[4]] <- tfbsTrack
gh_plots[[4]] <- grTrack
# plots[[1]]@dp@pars$fontsize <- 12
gh_plots[[1]]@dp <- plots[[3]]@dp # make track fonts and titles in the same theme
gh_plots[[5]] <- axTrack

geneModelFile <- paste0("plots/geneModel.conns.",gene,".",atac_clusterID,".pdf")
pdf(file = geneModelFile, width=10, height=6)
plotTracks(gh_plots, chr, from = regionStart, to = regionEnd, ylim = c(0,ymax), sizes=c(2,0.25,2,1,0.5))
dev.off()



