# this script will compare the cicero CCAN for each cell type identify overlapping interactions
# in the GeneHancer database within 50kb of DAR

library(data.table)
library(dplyr)
library(cicero)
library(here)
library(openxlsx)

# read in cicero connections generated by ciceroFindConns.R
Read_Cicero_Conns <- function(clusterID) {
  connsFile <- paste0("analysis_control/ccans/ciceroConns.control.",clusterID,".csv")
  filtered_cicero_conns <- fread(connsFile) %>%
    dplyr::select(Peak1, Peak2, coaccess) %>%
    dplyr::filter(coaccess > 0.1)
  return(filtered_cicero_conns)
}  

Read_DAR_Query_Region <- function(clusterID) {
  gh_query <- paste0("analysis_control/ccans/geneHancer/GeneHancerQuery_",clusterID,".bed")
  query_bed <- read.table(gh_query, header = FALSE)
  query_peak <- paste0(query_bed$V1,"_",query_bed$V2,"_",query_bed$V3)
  query_conns <- data.frame(Peak1 = query_peak, Peak2 = query_peak, coaccess = 0)
  return(query_conns)
}
  
# load the regions of interest (query)
Filter_Cicero_Conns_by_Region <- function(cicero_conns, query_conns) {
  # overlap the query bed file with the cicero connections file by making an interaction that covers the region
  cicero_conns$in_query <- compare_connections(cicero_conns, query_conns) 
  cicero_conns_in_region <- cicero_conns[cicero_conns$in_query == "TRUE",] # remove cicero conns not in query region
  # head(cicero_conns[cicero_conns$in_query == "TRUE",])
  # nrow(cicero_conns[cicero_conns$in_query == "TRUE",])
  # nrow(cicero_conns[cicero_conns$in_query == "FALSE",])
  return(cicero_conns_in_region)
}

# read in the geneHancer database for the cell type of interest
# there are two genehancer interaction databases that include "all" interactions and "de" for double elite stringent reactions
Prepare_Genehancer_Database <- function(clusterID, genehancer = NULL) {
  if(genehancer == "all") {
    gh_db_file <- paste0("analysis_control/ccans/geneHancer/GeneHancer_all_conns_",clusterID,".txt")
  } else if (genehancer == "de") {
    gh_db_file <- paste0("analysis_control/ccans/geneHancer/GeneHancer_de_conns_",clusterID,".txt")
  }
  
  gh_db <- read.table(gh_db_file, header = TRUE, comment.char = "")
  peak1 <- paste0(gh_db$X.chrom,"_",gh_db$chromStart,"_",gh_db$chromEnd)
  peak2 <- paste0(gh_db$X.chrom,"_",gh_db$chromStart,"_",gh_db$chromEnd)
  gh_db_conns <- data.frame(Peak1 = peak1, Peak2 = peak2, coaccess = 0.5)
  return(gh_db_conns)
}

Num_GH_Conns_in_Region <- function(gh_db_conns, query_conns) {
  # determine how many genehancer interactions are in the query region
  gh_db_conns$in_query <- compare_connections(gh_db_conns, query_conns)
  num_gh_db_conns_in_query <- nrow(gh_db_conns[gh_db_conns$in_query == "TRUE", ])
  return(num_gh_db_conns_in_query)
}  

FindOverlap_by_Coaccess <- function(coaccess_threshold, cicero_conns, gh_all_conns, gh_de_conns,
                                    num_gh_all_in_region, num_gh_de_in_region){
  cicero_conns <- dplyr::filter(cicero_conns, coaccess > coaccess_threshold)
  cicero_conns$in_gh_all <- compare_connections(cicero_conns, gh_all_conns, maxgap=100)
  num_overlap_gh_all <- nrow(cicero_conns[cicero_conns$in_gh_all == "TRUE",])
  total_conns <- nrow(cicero_conns)
  
  cicero_conns$in_gh_de <- compare_connections(cicero_conns, gh_de_conns, maxgap=100)
  num_overlap_gh_de <- nrow(cicero_conns[cicero_conns$in_gh_de == "TRUE",])
  
  conns_df <- data.frame(cicero_coaccess_threshold=coaccess_threshold,
                         cicero_in_gh_all=num_overlap_gh_all, 
                         prop_cicero_in_gh_all=num_overlap_gh_all/total_conns,
                         cicero_in_gh_de=num_overlap_gh_de,
                         prop_cicero_in_gh_de=num_overlap_gh_de/total_conns,
                         total_cicero_conns=total_conns,
                         total_gh_de_conns=num_gh_de_in_region,
                         total_gh_all_conns=num_gh_all_in_region)
  return(conns_df)
}

# wrapper function to call all the functions in sequence
Find_Overlap_Cicero_Genehancer <- function(clusterID) {
  print(paste0("Reading cicero connections for: ", clusterID))
  cicero_conns <- Read_Cicero_Conns(clusterID)
  
  print(paste0("Reading DAR query regions for: ", clusterID))
  query_conns <- Read_DAR_Query_Region(clusterID)
  
  print(paste0("Filtering cicero connections for: ", clusterID))
  cicero_conns <- Filter_Cicero_Conns_by_Region(cicero_conns, query_conns)
  
  print(paste0("Preparing genehancer database for: ", clusterID))
  gh_all_conns <- Prepare_Genehancer_Database(clusterID, genehancer = "all")
  gh_de_conns <- Prepare_Genehancer_Database(clusterID, genehancer = "de")
  
  print(paste0("Calculating number of genehancer connections in region for: ", clusterID))
  num_gh_all_in_region <- Num_GH_Conns_in_Region(gh_all_conns, query_conns)
  num_gh_de_in_region <- Num_GH_Conns_in_Region(gh_de_conns, query_conns)
  
  print(paste0("Finding overlap between cicero and genehancer for: ", clusterID))
  list.coaccess <- list(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)
  coaccess_threshold <- list.coaccess[[1]]
  overlap_multi_coaccess <- lapply(seq(list.coaccess), function(index) {
    coaccess_threshold <- list.coaccess[[index]]
    overlap_single_coaccess <- FindOverlap_by_Coaccess(coaccess_threshold, cicero_conns, gh_all_conns, gh_de_conns,
                            num_gh_all_in_region, num_gh_de_in_region)
    return(overlap_single_coaccess) 
  }) %>% 
     bind_rows()
  return(overlap_multi_coaccess)
}
###########################################################################################################
list.clusterID <- getSheetNames("analysis_control/dar.celltype.control.xlsx")
# list.clusterID <- c("PCT","PST","PODO")

list.overlap <- lapply(list.clusterID, function(clusterID) {
  Find_Overlap_Cicero_Genehancer(clusterID)
}) 

write.xlsx(list.overlap, file = "analysis_control/atac_overlap_ccans_geneHancer.xlsx", sheetName = list.clusterID)
# list.clusterID <- getSheetNames("analysis_control/atac_overlap_ccans_geneHancer.xlsx")
# list.overlap <- lapply(list.clusterID, function(sheetName) {
#   read.xlsx("analysis_control/atac_overlap_ccans_geneHancer.xlsx",
#   sheet= sheetName)
#   })

prop.overlap.df <-  lapply(seq(list.overlap), function(x) {
  df <- dplyr::select(list.overlap[[x]], "prop_cicero_in_gh_de")
}) %>%
  bind_cols() 
colnames(prop.overlap.df) <- list.clusterID
rownames(prop.overlap.df) <- list(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)

# plot the results by transposing the dataframe so coaccess threshold are the columns 
boxplot(t(prop.overlap.df),
        xlab="Cicero Coaccess Threshold",
        ylab="Mean Proportion of Cicero Connections in GeneHancer",
        col="red")

prop.overlap.df <-  lapply(seq(list.overlap), function(x) {
  df <- dplyr::select(list.overlap[[x]], "prop_cicero_in_gh_all")
}) %>%
  bind_cols() 
colnames(prop.overlap.df) <- list.clusterID
rownames(prop.overlap.df) <- list(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)

# plot the results by transposing the dataframe so coaccess threshold are the columns 
boxplot(t(prop.overlap.df),
        xlab="Cicero Coaccess Threshold",
        ylab="Mean Proportion of Cicero Connections in GeneHancer",
        col="red")

# remove the estimates for cicero coaccess threshold > 0.5
# the plot indicates that this is a plateau
boxplot(t(prop.overlap.df[1:5,]),
        xlab="Cicero Coaccess Threshold",
        ylab="Mean Proportion of Cicero Connections in GeneHancer",
        col="red",
        ylim=c(0,1))

# calculate a fisher exact for number of overlaps in coaccess < 0.1 vs > 0.5
num.overlap.gh_de <-  lapply(seq(list.overlap), function(x) {
  df <- dplyr::select(list.overlap[[x]], "cicero_in_gh_de")
}) %>%
  bind_cols()
colnames(num.overlap.gh_de) <- list.clusterID
rownames(num.overlap.gh_de) <- list(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)

total.num.cicero <-  lapply(seq(list.overlap), function(x) {
  df <- dplyr::select(list.overlap[[x]], "total_cicero_conns")
}) %>%
  bind_cols()
colnames(total.num.cicero) <- list.clusterID
rownames(total.num.cicero) <- list(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)



