# this script will create a list of regions 50kb upstream and downstream of cell-type-specific DAR
# generated by the find_atac_dar.R script. The regions are for querying the GeneHancer database to identify
# chromatin interactions present in that area to compare to the CCAN calculated by Cicero
library(openxlsx)
library(dplyr)
library(biomaRt)
library(here)

# load DAR and filter by adjusted pval, distance from DAR to nearest gene, average log-fold change of DAR,
# and the proportion of cells containing the DAR
list.clusterID <- getSheetNames("analysis_control/dar.celltype.control.xlsx")

list.genes_to_query <- sapply(list.clusterID, function(x){
    dar <- read.xlsx("analysis_control/dar.celltype.control.xlsx",
                   sheet = x, rowNames = TRUE) %>%
    rownames_to_column(var = "coord") %>%
    dplyr::filter(p_val_adj < 0.05) %>%
    dplyr::filter(distance < 50000) %>%
    dplyr::distinct(gene, .keep_all = TRUE) %>% # remove second occurrences of each gene
    dplyr::top_n(1000, avg_logFC) %>% # take top 1000 genes by log fold change of DAR
    dplyr::distinct(gene)
})

# function for returning a bed file for each gene with the desired coordinates
PullRegionBed <- function(genes, extend) {
  seqlevels <- c(seq(1,24),"X","Y")
  human = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
  bm <- getBM(attributes = c("hgnc_symbol","chromosome_name", "start_position", "end_position","ensembl_gene_id"),
              filters = "hgnc_symbol", values = genes, mart = human) %>%
              dplyr::filter(chromosome_name %in% seqlevels)
  regionStart <- bm$start_position - extend
  if(regionStart < 0) { # make sure coordinates are not negative at beginning of chrom
    regionStart = 1
  }
  regionEnd <- bm$end_position + extend # coordinates cannot extend past max of chrom
  chr <- paste0("chr", bm$chromosome_name)
  bed <- data.frame(chr, regionStart, regionEnd)
  return(bed)
}

# create a list of bed files to query corresponding to each cell type in the snATAC dataset
index <- seq(list.genes_to_query)
list.regions_to_query.bed <- lapply(index, function(x) {
  genes <- list.genes_to_query[[x]]
  PullRegionBed(genes, 50000)
})

# write the bed files
lapply(index, function(x) {
  bed <- list.regions_to_query.bed[[x]] 
  file <- paste0("analysis_control/ccans/geneHancer/GeneHancerQuery_",list.clusterID[[x]],".bed")
  write.table(bed, file = file, row.names = FALSE, quote = FALSE, col.names = FALSE)
})

# bed files have to be manually uploaded to query the ucsc genome table browser located at
# https://genome.ucsc.edu/cgi-bin/hgTables
# group: Regulation
# track: GeneHancer
# table: GH Interactions (DE) (geneHancerInteractionsDoubleElite) ##OR## GH Interactions (geneHancerInteractions)
# output format: all fields from selected table
# output file: "GeneHancer_de_conns_clusterID.txt"  ##OR## "GeneHancer_all_conns_clusterID.txt"





