# this script will compare the peaks generated by the cellranger-atac pipeline
# with DNAse hypersensitive regions obtained from PMID30760496
library(GenomicRanges)
library(Seurat)
library(Signac)
library(stringr)
library(plyranges)
library(openxlsx)

# function for identifying peaks within a given cell type and filtering for the proportion of cells containing the peak
Find_CR_Celltype_Peaks <- function(celltype, pct.ref.cells, seurat_agg) {
celltype_cr_peaks <- as.matrix(GetAssayData(seurat_agg, slot="counts")[, WhichCells(seurat_agg, ident=celltype)])
celltype_cr_peaks.filter.bed <- celltype_cr_peaks[rowSums(celltype_cr_peaks[, -1])/ncol(celltype_cr_peaks) > pct.ref.cells, ] %>% # peaks must be detected in at least 10% cells
  rownames() %>%
  str_split(pattern = ":|-", simplify = TRUE) %>%
  as.data.frame() %>%
  dplyr::rename("chr"="V1","start"="V2","end"="V3")
return(makeGRangesFromDataFrame(celltype_cr_peaks.filter.bed))
}

Find_CR_Peaks <- function(pct.ref.cells, seurat_agg) {
  cr_peaks <- GetAssayData(seurat_agg, slot="counts")
  cr_peaks.filter.bed <- cr_peaks[rowSums(cr_peaks[, -1])/ncol(cr_peaks) > pct.ref.cells, ] %>% # peaks must be detected in at least % cells
    rownames() %>%
    str_split(pattern = ":|-", simplify = TRUE) %>%
    as.data.frame() %>%
    dplyr::rename("chr"="V1","start"="V2","end"="V3")
  return(makeGRangesFromDataFrame(cr_peaks.filter.bed))
}

Find_CR_DAR <- function(clusterID, pct.ref.cells, darFile = "analysis_control/dar.celltype.control.xlsx") {
  bed <- read.xlsx(darFile, sheet=clusterID, rowNames = TRUE) %>%
    rownames_to_column(var="coord") %>%
    dplyr::filter(pct.1 > pct.ref.cells) %>%
    dplyr::select("coord") %>%
    column_to_rownames("coord") %>%
    rownames() %>%
    str_split(pattern = ":|-", simplify = TRUE) %>%
    as.data.frame() %>%
    dplyr::rename("chr"="V1","start"="V2","end"="V3")
  return(makeGRangesFromDataFrame(bed))
}

# function to prepare reference database
# bed files were called with hotspot v2 
PrepareDHSGRanges <- function(list.bed) {
  gr <- lapply(list.bed, function(file) {
    df <- read.table(file) 
    }) %>%
    bind_rows() %>% # create the union of bed files
    dplyr::select("V1","V2","V3") %>%
    dplyr::rename("chr"="V1","start"="V2","end"="V3") %>%
    makeGRangesFromDataFrame() %>%
    reduce() # collapse intervals together
}


# function to count overlaps between REF and QUERY
GetOverlaps <- function(query.gr, ref.gr, pct.overlap) {
  hits <- findOverlaps(query.gr, ref.gr)
  overlaps <- pintersect(query.gr[queryHits(hits)], ref.gr[subjectHits(hits)])
  percentOverlap <- width(overlaps) / width(query.gr[queryHits(hits)])
  hits <- hits[percentOverlap > pct.overlap]
  celltype.peaks.filter.gr <- query.gr[unique(queryHits(hits))]
  total_query <- length(query.gr) # total number of query peaks
  in_ref <- length(celltype.peaks.filter.gr) # number of query peaks with >90% overlap with REF
  prop_in_ref <- in_ref / total_query
  data.frame(in_ref, total_query, prop_in_ref)
}


##########################################################################

glom_dna_bedFiles <- 
  c("comparison_human_datasets/sieber_PMID30760496/GSM3196013_DS35973-LN30328-AG6995-peaks.bed.gz",
    "comparison_human_datasets/sieber_PMID30760496/GSM3196014_DS39386-LN32272-AG3852-peaks.bed.gz",
    "comparison_human_datasets/sieber_PMID30760496/GSM3196015_DS40507-LN33574-AG7000-peaks.bed.gz",
    "comparison_human_datasets/sieber_PMID30760496/GSM3196016_DS41157-LN33957-AG7003-peaks.bed.gz")

tubule_dna_bedFiles <- 
  c("comparison_human_datasets/sieber_PMID30760496/GSM3196017_DS27824-LN29654-AG3899-peaks.bed.gz",
    "comparison_human_datasets/sieber_PMID30760496/GSM3196018_DS37969-LN31356-AG6997-peaks.bed.gz",
    "comparison_human_datasets/sieber_PMID30760496/GSM3196019_DS41396-LN34037-AG7005-peaks.bed.gz")

podo_dna_bedFiles <- 
  c("comparison_human_datasets/sieber_PMID30760496/GSM3196020_DS26685-LN26974-AG6994-peaks.bed.gz",
    "comparison_human_datasets/sieber_PMID30760496/GSM3196021_DS26687-LN34624-AG6216-peaks.bed.gz")

# read in the aggregated snATAC-seq object
atacAggr <- readRDS("cellranger_atac_prep/atacAggr_sub97_control.rds")
atacAggr.bed <- read.table("cellranger_atac_aggr_control/outs/peaks.bed")
darFile <- "analysis_control/dar.celltype.control.xlsx"

# prepare references
glom_DHS.gr <- PrepareDHSGRanges(glom_dna_bedFiles)
tubule_DHS.gr <- PrepareDHSGRanges(tubule_dna_bedFiles)
podo_DHS.gr <- PrepareDHSGRanges(podo_dna_bedFiles)
list.DHS.gr <- list(glom_DHS.gr,tubule_DHS.gr, podo_DHS.gr)
names(list.DHS.gr) <- c("glom","tubule","podo")

# find the cellranger peaks and DAR to compare to the DHS
idents <- levels(atacAggr)
pct.ref.cells <- 0.01
cr.gr <- Find_CR_Peaks(seurat_agg=atacAggr, pct.ref.cells = pct.ref.cells)
list.cr.celltype.gr <- lapply(idents, function(clusterID) {Find_CR_Celltype_Peaks(clusterID, pct.ref.cells=pct.ref.cells, seurat_agg=atacAggr)})
list.cr.dar.gr <- lapply(idents, function(clusterID) {Find_CR_DAR(clusterID=clusterID, pct.ref.cells=pct.ref.cells)})
names(list.cr.celltype.gr) <- idents


# for a threshold of 0.01, 0.05, 0.1, 0.2 pct cells with a given cellranger peak calculate the overlap with DHS for glom and
# tubulointerstitium and plot as a bar plot
thresholds <- c(0, 0.01, 0.05, 0.1, 0.2)
list.cr.gr <- lapply(thresholds, function(threshold) {
  Find_CR_Peaks(seurat_agg = atacAggr, pct.ref.cells = threshold)})

list.cr_in_DHS_by_threshold <- lapply(list.cr.gr, function(query.gr) {
  df <- lapply(list.DHS.gr, function(ref.gr) {
    GetOverlaps(query.gr, ref.gr, pct.overlap=0) # cellranger peaks are much wider
  }) %>%
    bind_rows() 
  rownames(df) <- names(list.DHS.gr)
  return(df)
}) 
names(list.cr_in_DHS_by_threshold) <- thresholds

# prepare dataframe to generate box plots
prop.overlap.df <-  lapply(seq(list.cr_in_DHS_by_threshold), function(x) {
  df <- dplyr::select(list.cr_in_DHS_by_threshold[[x]], "prop_in_ref")
}) %>%
  bind_cols() 
colnames(prop.overlap.df) <- thresholds
rownames(prop.overlap.df) <- names(list.DHS.gr)

# only plot the glom and tubule rows
library(reshape)
toplot <- prop.overlap.df[-3,] %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var="threshold") %>%
  melt("threshold")

ggplot(toplot, aes(x=threshold, y=value, fill=variable)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("Threshold for Proportion of Cells with Cellranger Peak") +
  ylab("Proportion of Cellranger Peaks Overlapping with DHS Sites")





# # find cellranger peaks in DHS
# df.cr_in_DHS.overlap <- lapply(list.DHS.gr, function(ref.gr) {
#   df <- GetOverlaps(cr.gr, ref.gr, pct.overlap=0)
# }) %>%
#   bind_rows()
# rownames(df.cr_in_DHS.overlap) <- names(list.DHS.gr)
# 
# # find DHS in cellranger peaks 
# df.DHS_in_cr.overlap <- lapply(list.DHS.gr, function(query.gr) {
#   df <- GetOverlaps(query.gr, cr.gr, pct.overlap=0.9)
# }) %>%
#   bind_rows()
# rownames(df.DHS_in_cr.overlap) <- names(list.DHS.gr)
# 
# # find DHS sites in cellranger celltype peaks
# list.DHS_in_cr_celltype.overlap <- lapply(list.DHS.gr, function(query.gr) {
#   df <- lapply(list.cr.celltype.gr, function(ref.gr) {
#     GetOverlaps(query.gr, ref.gr, pct.overlap=0.9)
#   }) %>%
#   bind_rows() 
#   rownames(df) <- idents
#   return(df)
# }) 
# 
# # find DHS sites in cellranger DAR
# list.DHS_in_cr_dar.overlap <- lapply(list.DHS.gr, function(query.gr) {
#   df <- lapply(list.cr.dar.gr, function(ref.gr) {
#     GetOverlaps(query.gr, ref.gr, pct.overlap=0.9)
#   }) %>%
#     bind_rows() 
#   rownames(df) <- idents
#   return(df)
# }) 
# 
# # find cellranger celltype peaks in DHS sites
# list.cr_celltype_in_DHS.overlap <- lapply(list.cr.celltype.gr, function(query.gr) {
#   df <- lapply(list.DHS.gr, function(ref.gr) {
#     GetOverlaps(query.gr, ref.gr, pct.overlap=0) # cellranger peaks are much wider
#   }) %>%
#     bind_rows() 
#   rownames(df) <- names(list.DHS.gr)
#   return(df)
# }) 
# names(list.cr_in_DHS.overlap) <- idents
# 
# # find cellranger DAR in DHS sites
# list.cr_dar_in_DHS.overlap <- lapply(list.cr.dar.gr, function(query.gr) {
#   df <- lapply(list.DHS.gr, function(ref.gr) {
#     GetOverlaps(query.gr, ref.gr, pct.overlap=0) # cellranger peaks are much wider
#   }) %>%
#     bind_rows() 
#   rownames(df) <- names(list.DHS.gr)
#   return(df)
# }) 
# names(list.cr_dar_in_DHS.overlap) <- idents
# 
# 
# 
# # table(!is.na(findOverlaps(celltype.peaks.gr, podo_dna.gr, select="arbitrary"))) %>%
# #   as.data.frame(row.names = TRUE) %>%
# #   t() %>%
# #   as.data.frame() %>%
# #   dplyr::rename(F = 'FALSE', T = 'TRUE') %>% 
# #   dplyr::mutate(prop = T/(T+F))
# 
# 
# 
# 
# 
